# Generated by Django 4.1 on 2022-08-21 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('rating', models.IntegerField(verbose_name='rating')),
                ('year', models.IntegerField(verbose_name='year')),
                ('director', models.CharField(max_length=50, verbose_name='director')),
                ('description', models.TextField()),
            ],
        ),
    ]
