# Generated by Django 4.1 on 2022-08-22 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_movie_model_img_alter_movie_model_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie_model',
            name='link',
            field=models.CharField(default='ggg', max_length=200, verbose_name='link'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movie_model',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
