# Generated by Django 4.1 on 2022-08-22 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_movie_model_link_alter_movie_model_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie_model',
            name='visit_count',
            field=models.IntegerField(default=0, verbose_name='count'),
        ),
    ]
